#!/usr/bin/env python3
# Copyright 2026 Arm Limited and/or its affiliates.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
"""Generate all_ops.cproject.yml selecting every operator component the pack
ships.

The smoke test enables a single operator; this project enables *every* operator
component discovered by op_guards, so one consumer build links every operator's
generated registration, forward declaration and kernel source together. The
component list is derived from the same op_guards.discover_components used by
the pack's PDSC generator, so the project can never select a component the pack
does not ship (or miss one it does).

"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parents[2] / "scripts"
sys.path.insert(0, str(_SCRIPTS))

from op_guards import (  # type: ignore[import-not-found]  # noqa: E402
    discover_components,
)

try:
    from generate_components import (  # type: ignore[import-not-found]  # noqa: E402
        _op_uses_cmsis_nn,
    )
except ImportError:  # pragma: no cover - generate_components always importable here
    _op_uses_cmsis_nn = None


_HEADER = """\
# Copyright 2026 Arm Limited and/or its affiliates.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
# AUTO-GENERATED by gen_cproject.py -- do not edit by hand.
# Selects every ExecuTorch operator component so a single consumer build links
# the whole operator surface of the pack.

project:
  packs:
    - pack: PyTorch::ExecuTorch
"""

# Components every ExecuTorch consumer needs, independent of which ops are on.
# CMSIS-Compiler retarget: CORE supplies the per-toolchain low-level glue (newlib
# _write for GCC, the Arm C library retarget for AC6, picolibc FILE streams for
# AtFE/CLANG) and routes stdout/stderr to stdout_semihosting.c.
_BASE_COMPONENTS = (
    "ARM::CMSIS:CORE",
    "ARM::Device:Startup&C Startup",
    "ARM::CMSIS-Compiler:CORE",
    "ARM::CMSIS-Compiler:STDOUT:Custom",
    "ARM::CMSIS-Compiler:STDERR:Custom",
    "Machine Learning:ExecuTorch:Runtime",
    "Machine Learning:ExecuTorch:Kernel Utils",
    "Machine Learning:ExecuTorch:Kernel Registration",
)

# Satisfies the "CMSIS-NN" condition that Cortex-M ops routing through CMSIS-NN
# carry (see PyTorch.ExecuTorch.pdsc.tpl). Only added when such an op is present.
_CMSIS_NN_COMPONENT = "ARM::CMSIS:NN Lib"

# Project-wide options emitted after `packs:` and before `components:`.
_PROJECT_OPTIONS = """\
  define:
    # Route ExecuTorch ET_LOG() through et_pal_override.cpp -> printf ->
    # semihosting so runtime load/execute failures are visible on the FVP.
    - ET_LOG_ENABLED: 1
    - ET_MIN_LOG_LEVEL: Debug

  # Resolve project-local headers (random_device_shim.h) for the -include below,
  # including from pack component sources.
  add-path:
    - .

  # add-path is C/C++ only; the assembler needs add-path-asm so
  # embedded_models_blob.S resolves its relative `.incbin "models/..."` paths
  # regardless of the build working directory.
  add-path-asm:
    - .
"""

# Per-compiler linker scripts, toolchain misc flags, and the App sources that
# retarget I/O + logging. GCC and CLANG share the GNU script (lld accepts it);
# AC6 uses the scatter file. The every-operator image (~5-6 MB code + ~22 MB
# static pools) overflows the ARMCM55 device default (256 KB ROM / 128 KB RAM),
# so both layouts place it in the Corstone-300 DDR window. See ARMCM55_large.ld,
# ARMCM55_large.sct, REPORT.md and FEEDBACK.md for the why of each entry.
_LINKER_MISC_GROUPS = """
  linker:
    - script: ./ARMCM55_large.ld
      for-compiler: GCC
    - script: ./ARMCM55_large.ld
      for-compiler: CLANG
    - script: ./ARMCM55_large.sct
      for-compiler: AC6

  misc:
    # AtFE/CLANG: force hard-float and -include the random_device shim so the RNG
    # ops build against AtFE's libc++ (_LIBCPP_HAS_RANDOM_DEVICE 0; the shim
    # self-guards, so it is a no-op for GCC/AC6). NOTE: re-asserting -mcpu here
    # does NOT undo cbuild CLANG.cmake's -mfpu=fpv5-sp-d16, which disables MVE.fp
    # (__ARM_FEATURE_MVE 3 -> 1); the Cortex-M Helium ops still need the op-guard
    # patch (FP bit) and/or the toolbox -mfpu fix. See REPORT.md.
    - for-compiler: CLANG
      C: [-mcpu=cortex-m55, -mfloat-abi=hard]
      CPP: [-mcpu=cortex-m55, -mfloat-abi=hard, -include, random_device_shim.h]
      ASM: [-mcpu=cortex-m55, -mfloat-abi=hard]
      Link: [-mcpu=cortex-m55, -mfloat-abi=hard]
    # AC6: armlink's RW-data decompressor hardfaults at startup; disable RW
    # compression so scatter-load does a plain copy.
    - for-compiler: AC6
      Link: [--datacompressor=off]

  groups:
    - group: App
      files:
        - file: ./main.cpp
        # Per-op test models embedded into .rodata (.incbin) by
        # gen_embedded_models.py. A stub (0 models) is emitted when the model
        # export step has not run, so build/link coverage works without torch.
        - file: ./embedded_models.cpp
        - file: ./embedded_models_blob.S
        - file: ./stdout_semihosting.c
        - file: ./et_pal_override.cpp
"""


def _needs_cmsis_nn(source_dir: Path, components: list) -> bool:
    if _op_uses_cmsis_nn is None:
        # Conservative fallback: any Cortex-M op may pull in CMSIS-NN.
        return any(c.category == "Cortex-M" for c in components)
    return any(
        c.category == "Cortex-M" and _op_uses_cmsis_nn(source_dir / c.source_file)
        for c in components
    )


def build_cproject(source_dir: Path) -> str:
    """Render all_ops.cproject.yml content for the operators found under
    ``source_dir`` (the staged pack tree or the repo root).
    """
    components = discover_components(source_dir)
    if not components:
        raise SystemExit(f"No operator components discovered under {source_dir}")

    lines = [_HEADER, _PROJECT_OPTIONS, "  components:"]
    for component in _BASE_COMPONENTS:
        lines.append(f"    - component: {component}")
    if _needs_cmsis_nn(source_dir, components):
        lines.append(f"    - component: {_CMSIS_NN_COMPONENT}")
    for c in components:
        lines.append(
            f"    - component: Machine Learning:ExecuTorch Operators:{c.category} {c.name}"
        )
    lines.append(_LINKER_MISC_GROUPS)
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate all_ops.cproject.yml selecting every operator component"
    )
    parser.add_argument(
        "--source-dir",
        "-s",
        required=True,
        help="Staged pack tree or repo root containing kernels/ and backends/",
    )
    parser.add_argument(
        "--output",
        "-o",
        default=str(Path(__file__).resolve().parent / "all_ops.cproject.yml"),
        help="Output path for all_ops.cproject.yml",
    )
    args = parser.parse_args()

    content = build_cproject(Path(args.source_dir))
    Path(args.output).write_text(content)
    n_ops = content.count("ExecuTorch Operators:")
    print(f"Wrote {args.output}: {n_ops} operator components")


if __name__ == "__main__":
    main()
