#!/usr/bin/env python3
# Copyright 2026 Arm Limited and/or its affiliates.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
"""Embed the per-op test models into the all-ops firmware.

Reads ``models/manifest.json`` (produced by generate_test_models.py) and emits
three sources the consumer build compiles in:

  * embedded_models_blob.S  -- ``.incbin`` of each model.pte / input_*.bin /
    expected_*.bin into .rodata, so the image is self-contained and needs no
    semihosting filesystem access at run time. (The ``.S`` stem is distinct
    from embedded_models.cpp to avoid AC6's cbuild2cmake object-name clash.)
  * embedded_models.cpp     -- the g_embedded_models[] table referencing the
    blob symbols, plus per-model input/expected arrays.
  * embedded_models.h       -- the EmbeddedModel/EmbeddedBuffer structs.

The ``.incbin`` paths are RELATIVE to this directory (``models/<dir>/<file>``).
The consumer project carries ``add-path: [.]`` -> ``-I<project-dir>``, which the
assembler searches for ``.incbin``, so the same generated file resolves whether
the build runs on the host or inside the Docker build container (host absolute
paths would not exist in the container).

If ``models/manifest.json`` is absent (build/link-coverage only, no torch
export step), a valid empty stub is emitted so the image still links and runs
(reporting 0/0). Re-run whenever the manifest or any model dir changes.

"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent

_H_CONTENT = """\
// AUTO-GENERATED by gen_embedded_models.py -- do not edit.
#pragma once

#include <cstddef>

struct EmbeddedBuffer {
    const unsigned char* data;
    std::size_t size;
};

struct EmbeddedModel {
    const char* op;
    const char* dir;
    const unsigned char* pte_data;
    std::size_t pte_size;
    const EmbeddedBuffer* inputs;
    std::size_t num_inputs;
    const EmbeddedBuffer* expected;
    std::size_t num_outputs;
    float atol;
    float rtol;
};

extern const EmbeddedModel g_embedded_models[];
extern const std::size_t g_embedded_models_count;
"""

# A 1-element dummy array (never indexed: count is 0) keeps g_embedded_models a
# well-formed definition when no models are embedded -- C++ has no zero-length
# arrays.
_CPP_STUB = """\
// AUTO-GENERATED by gen_embedded_models.py -- do not edit.
// Stub: no models/manifest.json found (build/link coverage only).
#include "embedded_models.h"

const EmbeddedModel g_embedded_models[] = {
    { "", "", nullptr, 0, nullptr, 0, nullptr, 0, 0.0f, 0.0f },
};
const std::size_t g_embedded_models_count = 0;
"""

_S_STUB = """\
/* AUTO-GENERATED by gen_embedded_models.py -- do not edit. */
/* Stub: no models embedded (build/link coverage only). */
"""


def _sym(prefix: str, dirname: str, suffix: str = "") -> str:
    name = f"_emb_{prefix}_{dirname}"
    return f"{name}_{suffix}" if suffix else name


def build(models_dir: Path, output_dir: Path) -> tuple[str, str, str, int, int]:
    """Return (blob_s, cpp, header, n_models, n_bytes)."""
    manifest_path = models_dir / "manifest.json"
    if not manifest_path.exists():
        return _S_STUB, _CPP_STUB, _H_CONTENT, 0, 0

    manifest = json.loads(manifest_path.read_text())
    # .incbin paths are relative to output_dir (resolved via -I<project-dir>).
    rel_models = Path(os.path.relpath(models_dir, output_dir))

    s_lines = [
        "/* AUTO-GENERATED by gen_embedded_models.py -- do not edit. */",
        '    .section .rodata.embedded_models,"a",%progbits',
        "    .balign 16",
        "",
    ]
    cpp_lines = [
        "// AUTO-GENERATED by gen_embedded_models.py -- do not edit.",
        '#include "embedded_models.h"',
        "",
        'extern "C" {',
    ]
    table_entries: list[str] = []
    n_bytes = 0

    for entry in manifest:
        d = entry["dir"]
        op = entry["op"]
        atol = float(entry.get("atol", 1e-3))
        rtol = float(entry.get("rtol", 1e-3))
        if not (models_dir / d / "model.pte").exists():
            print(f"warning: missing {models_dir / d / 'model.pte'}", file=sys.stderr)
            continue

        def emit(prefix: str, fname: str, suffix: str = "", d: str = d) -> bool:
            nonlocal n_bytes
            disk = models_dir / d / fname
            if not disk.exists():
                print(f"warning: missing {disk}", file=sys.stderr)
                return False
            n_bytes += disk.stat().st_size
            s = _sym(prefix, d, suffix)
            incbin = (rel_models / d / fname).as_posix()
            s_lines.extend(
                [
                    "    .balign 16",
                    f"    .global {s}_start",
                    f"{s}_start:",
                    f'    .incbin "{incbin}"',
                    f"    .global {s}_end",
                    f"{s}_end:",
                    "",
                ]
            )
            cpp_lines.extend(
                [
                    f"extern const unsigned char {s}_start[];",
                    f"extern const unsigned char {s}_end[];",
                ]
            )
            return True

        emit("pte", "model.pte")
        inputs = entry.get("inputs", [])
        outputs = entry.get("outputs", [])
        for i, inp in enumerate(inputs):
            emit("in", inp["file"], str(i))
        for i, out in enumerate(outputs):
            emit("exp", out["file"], str(i))

        cpp_lines.append('}  // extern "C"')
        cpp_lines.append("")
        cpp_lines.append(f"static const EmbeddedBuffer kInputs_{d}[] = {{")
        for i in range(len(inputs)):
            s = _sym("in", d, str(i))
            cpp_lines.append(
                f"    {{ {s}_start, static_cast<std::size_t>({s}_end - {s}_start) }},"
            )
        cpp_lines.append("};")
        cpp_lines.append(f"static const EmbeddedBuffer kExpected_{d}[] = {{")
        for i in range(len(outputs)):
            s = _sym("exp", d, str(i))
            cpp_lines.append(
                f"    {{ {s}_start, static_cast<std::size_t>({s}_end - {s}_start) }},"
            )
        cpp_lines.append("};")
        cpp_lines.append('extern "C" {')

        pte = _sym("pte", d)
        table_entries.append(
            f'    {{ "{op}", "{d}",\n'
            f"      {pte}_start, static_cast<std::size_t>({pte}_end - {pte}_start),\n"
            f"      kInputs_{d}, {len(inputs)},\n"
            f"      kExpected_{d}, {len(outputs)},\n"
            f"      {atol}f, {rtol}f }},"
        )

    cpp_lines.append('}  // extern "C"')
    cpp_lines.append("")
    cpp_lines.append("const EmbeddedModel g_embedded_models[] = {")
    cpp_lines.extend(table_entries)
    cpp_lines.append("};")
    cpp_lines.append("")
    cpp_lines.append(
        "const std::size_t g_embedded_models_count = "
        "sizeof(g_embedded_models) / sizeof(g_embedded_models[0]);"
    )
    cpp_lines.append("")
    return (
        "\n".join(s_lines),
        "\n".join(cpp_lines),
        _H_CONTENT,
        len(table_entries),
        n_bytes,
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Embed per-op test models into the all-ops firmware"
    )
    parser.add_argument(
        "--models-dir",
        default=str(_HERE / "models"),
        help="directory with per-op model dirs + manifest.json",
    )
    parser.add_argument(
        "--output-dir",
        default=str(_HERE),
        help="where to write embedded_models.{h,cpp,_blob.S}",
    )
    args = parser.parse_args()

    models_dir = Path(args.models_dir).resolve()
    output_dir = Path(args.output_dir).resolve()
    blob_s, cpp, header, n_models, n_bytes = build(models_dir, output_dir)

    (output_dir / "embedded_models_blob.S").write_text(blob_s)
    (output_dir / "embedded_models.cpp").write_text(cpp)
    (output_dir / "embedded_models.h").write_text(header)

    if n_models:
        print(f"embedded {n_bytes:,} bytes across {n_models} models -> {output_dir}")
    else:
        print(f"no models/manifest.json under {models_dir}: wrote empty stub")
    return 0


if __name__ == "__main__":
    sys.exit(main())
